### ISSUE TITLE
Signal 11 encountered when running 3d example

### ISSUE THREAD

**Issue by DarrenLynch** [capaulson/pyKriging#19] opened 2017-05-17 19:49 UTC
Hi guys, I'm new to all this. I am trying to evaluate pyKriging for mechanical design optimisation. I can run the 2D examples fine, however, when running the 3D example I get a signal 11 python crash. I presume this is just me not having enough memory? 

If you need more info I am more than happy oblige. 

Many thanks,
Darren

**Comment by capaulson** [comment] 2017-05-30 16:00
That's surprising. It sounds like this may likely be caused by trying to plot the results. If you comment out the plot commands in the 3D case, does it run?

**Comment by DarrenLynch** [comment] 2017-05-30 19:44
Hi capaulson, yes runs fine if I comment out the plot. I'm running ubuntu not windows is this likely to cause issues?

**Comment by capaulson** [comment] 2017-05-30 20:06
In a python terminal, can you run:
```import mayavi.mlab as mlab```
Please post the results.

**Comment by DarrenLynch** [comment] 2017-05-30 21:07
darren@darren-VirtualBox:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mayavi.mlab as mlab
>>> 

Nothing else output, Cheers Darren

**Comment by capaulson** [comment] 2017-05-31 14:50
Can you try running this: 
```
# Create the data.
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
from mayavi import mlab
s = mlab.mesh(x, y, z)
mlab.show()
```

This is a demo from Mayavi (http://docs.enthought.com/mayavi/mayavi/mlab.html). Does it plot?

**Comment by DarrenLynch** [comment] 2017-06-15 17:33
Hi, sorry I have been away a while. No this didn't plot, I expected it to fail at the plotting stage however if failed at the s = mlab.mesh(x, y, z) stage with error: 'Segmentation fault (core dumped)'

**Comment by capaulson** [comment] 2017-06-17 03:41
Right, so this sounds like an issues with your install of mayavi. It could be just an issue with the install, so you could try rebuilding/re-installing the library. It might also have something to do with virtualbox. Not sure exactly how mayavi works on a virtual box. 

I'm going to close this out, as this is an issue related for another library.

**Closed by capaulson** 2017-06-17 03:41 UTC
