### ISSUE TITLE
How to eliminate the randomness of the kriging model?

### ISSUE THREAD

**Issue by hantongeee** [capaulson/pyKriging#26] opened 2017-07-10 01:11 UTC
I am using the pyKriging package to build a surrogate model. And I find that when I input the same training data, the predict values are not the same for different trials. And I use the simplest kriging function, that is : k = kriging(X, y,)  and k.train(). The randomness of the kriging is unexpected for me, so could I eliminate it?

**Comment by capaulson** [comment] 2017-07-16 04:51
Can you provide a sample data set to reproduce this issue and provide details on what you define to be acceptable noise? It is difficult to understand the magnitude of the noise you're seeing from your comment. In general, this software is configured to work well on many types of problems, but not on all problems. Because this software assumes a multi-modal hyperparameter space for training the model, stochastic optimizers are used.  If you're solving a very difficult optimization problem, you may need to dial up the number of search iterations until you reach convergence. That said, any specific advise depends on the complexity of your data set and what you view as acceptable noise. Hope this helps @hantongeee .

**Comment by capaulson** [comment] 2017-07-22 04:58
closing for now, please re-open with more details

**Closed by capaulson** 2017-07-22 04:58 UTC
